# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poems?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: sam404
#mybatis-plus: #myabtis plus的mapper的xml文件的扫描路径
#  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081

